In [1]:
import numpy as np

from Utilities.dataloader import EEGDataLoader

In [9]:
from torchvision.transforms import Compose
from Utilities.transforms import minmax

transforms = Compose([
    minmax,
])

In [10]:
dl = EEGDataLoader("./dataset", transforms)

In [11]:
signal, label = dl.__getitem__(0)

In [12]:
signal

[array([0.3383877 , 0.35159096, 0.3271622 , ..., 0.2492147 , 0.29051536,
        0.33598888], dtype=float32),
 array([0.38666904, 0.36958817, 0.34857875, ..., 0.19699053, 0.21049109,
        0.23203182], dtype=float32),
 array([0.3151038 , 0.26049662, 0.2306034 , ..., 0.6687113 , 0.6867463 ,
        0.72542495], dtype=float32),
 array([0.5437487 , 0.5043528 , 0.44410792, ..., 0.43372348, 0.48839432,
        0.5319283 ], dtype=float32),
 array([0.40796044, 0.40520126, 0.39020896, ..., 0.28931487, 0.3198051 ,
        0.34577546], dtype=float32),
 array([0.31134108, 0.35672542, 0.40589893, ..., 0.5809113 , 0.5930332 ,
        0.6036129 ], dtype=float32),
 array([0.32619557, 0.33155835, 0.34856895, ..., 0.5139507 , 0.51372766,
        0.5328135 ], dtype=float32),
 array([0.7257626 , 0.7203146 , 0.63586664, ..., 0.17740795, 0.19802615,
        0.20372914], dtype=float32),
 array([0.72411835, 0.6755562 , 0.6118929 , ..., 0.47111815, 0.48645443,
        0.5012773 ], dtype=float32),
 array([0.

In [ ]:
label